{
    'name': "Boraq HR GOSI",
    'version': '14.0.1.0.1',
    'summary': """GOSI Contribution for Saudi Government""",
    'description': """GOSI Contribution for Saudi Government From Employee and Company""",
    'category': 'Human Resources',
    'author': 'Boraq-Group',
    'company': 'Boraq-Group',
    'maintainer': 'Boraq Group',
    'website': "https://boraq-group.com",
    'depends': ['hr_payroll',
                'hr_contract'],
    'data': [
        'views/gosi_view.xml',
        'views/sequence.xml',
        'data/rule.xml',
        'security/ir.model.access.csv',
    ],
    'demo': [],
    "images": ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'price': 180,
    "currency":  "EUR",
}
